version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=cinema_user
      - DB_PASS=cinema_password
      - DB_NAME=cinema

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cinema
      MYSQL_USER: cinema_user
      MYSQL_PASSWORD: cinema_password
    volumes:
      - db_data:/var/lib/mysql
      - ./database/cinema.sql:/docker-entrypoint-initdb.d/cinema.sql

volumes:
  db_data:

